SecRule SERVER_PORT "@streq 30000" phase:1,id:339852,pass,t:none,nolog,noauditlog,skipAfter:END_RBL

SecRule REMOTE_ADDR "@ipMatchFromFile /etc/asl/whitelist" phase:1,pass,t:none,id:318743,nolog,noauditlog,skipAfter:END_RBL

SecRule REMOTE_ADDR "@rbl rbl.interserver.net"  \
"phase:1,t:none,deny,status:403,nolog,auditlog,id:350000,rev:2,msg:'Global RBL Match: IP is on the rbl.interserver.net Blacklist',severity:'3',redirect:https://sigs.interserver.net/blocked?ref=%{HTTP_HOST}%{REQUEST_URI}&port=%{SERVER_PORT}"

SecMarker END_RBL
