SecRequestBodyAccess on

<IfModule !Litespeed>
	SecUploadDir /tmp
	SecUploadKeepFiles RelevantOnly
</IfModule>

SecUploadFileMode 0644
SecRule FILES_TMPNAMES "@inspectFile /opt/scan.sh" \
        "phase:2,t:none,id:351000,rev:1,severity:2,msg:'InterServer Upload Malware Scanner: Malicious File upload attempt detected and blocked',log,deny,auditlog,status:403"

<LocationMatch /wp-admin/async-upload.php>
SecRuleRemoveById 351000
</LocationMatch>

<LocationMatch /admin/index.php>
SecRuleRemoveById 382242
</LocationMatch>

<LocationMatch /wp-admin/media-upload.php>
SecRuleRemoveById 351000
</LocationMatch>

<LocationMatch /wp-admin/edit.php>
SecRuleEngine Off
</LocationMatch>

<LocationMatch /wp-admin/themes.php>
SecRuleEngine Off
</LocationMatch>

<LocationMatch /wp-admin/post.php>
SecRuleEngine Off
</LocationMatch>

<LocationMatch /wp-admin/post-new.php>
SecRuleEngine Off
</LocationMatch>

<LocationMatch /wp-admin/install.php>
SecRuleEngine Off
</LocationMatch>

<LocationMatch /wp-admin/theme-editor.php>
SecRuleEngine Off
</LocationMatch>

<LocationMatch /captcha.png.php>
SecRuleRemoveById 341137
</LocationMatch>

# below these are litespeed only
# that normally is due to speed
<IfModule Litespeed>
# rules causing issues 12/12/2017 ZDI-618-51253
SecRuleRemoveById 381209

#cscart error DSW-633-82389
SecRuleRemoveById 382241

#CVE-2018-6389 temporary fix
SecRule REQUEST_URI "@rx (?i:/wp-admin/load-scripts.php?.*?(load%5B%5D|load\[\]|load%5B\]|load\[%5D)=([^&,]*,){20,})" "id:999001,msg:'Potential use of CVE-2018-6389',deny"

SecRule QUERY_STRING "z3=RUJja2NELnBocA==" "id:999002,msg:'Potential use of indoxploit',deny"

SecRule REQUEST_URI "apikey\.php\?test=hello" "id:999003,msg:'Denied apikey.php access check',deny"

SecRule QUERY_STRING "z3=RUJja2NELnBocA==" "id:999004,msg:'Potential use of indoxploit',deny"

SecRule QUERY_STRING "z3=YldPTU5YLnBocA==" "id:999005,msg:'Potential use of indoxploit',deny"

SecRule REQUEST_URI "/wp-content/plugins/hello\.php\?cookie=1" "id:999006,msg:'Denied hello dolly malware insert',deny"

SecRule QUERY_STRING ");&eval=die(" "id:999007,msg:'Blocked known eval malware string',deny"

SecRule QUERY_STRING "php5=print(md5(wp)" "id:999008,msg:'Blocked bot malware string',deny"

SecRule QUERY_STRING "z3=dElJZ1RlLnBocA==" "id:999009,msg:'Potential use of indoxploit',deny"

SecRule QUERY_STRING "spanskys_filename=1234.txt" "id:999010,msg:'Recon query string spanskys_filename',deny"

SecRule QUERY_STRING "z3=OW5FbWlWLnBocA==" "id:999011,msg:'Potential use of indoxploit',deny"

# Drupal CVE-2018-7600
# SPECIFIC: Block #submit #validate #process #pre_render #post_render #element_validate #after_build #value_callback parameters
SecRule &ARGS_NAMES|&REQUEST_COOKIES_NAMES "@gt 0" "phase:2,log,chain,id:999011,t:none,block"
SecRule ARGS_NAMES|REQUEST_COOKIES_NAMES "#(submit|validate|pre_render|post_render|element_validate|after_build|value_callback|process|access_callback|lazy_builder)|\[#(submit|validate|pre_render|post_render|element_validate|after_build|value_callback|process|access_callback|lazy_builder)" "t:none,t:utf8toUnicode,t:urlDecodeUni,t:removeNulls,t:cmdLine,t:removeWhitespace"

#http://www.bigfinder.de/?c=ws&q=wordpress+setup+configuration+file&v=1
SecRule REQUEST_URI "/wp-admin/setup-config.php" "chain,id:999012,phase:2,t:none,deny,auditlog,log,status:403,msg:'InterServer blocked setup-config.php recon',rev:1,severity:2"
SecRule REQUEST_HEADERS:Referer "^https?://(www\.)?bigfinder\.de/?" "t:none"


</IfModule>
