#!/bin/sh

 #-
 # Copyright (c) 2006 InterServer, Inc.
 # All rights reserved.
 #
 # Redistribution and use in source and binary forms, with or without
 # modification, are permitted provided that the following conditions
 # are met:
 # 1. Redistributions of source code must retain the above copyright
 #    notice, this list of conditions and the following disclaimer.
 # 2. Redistributions in binary form must reproduce the above copyright
 #    notice, this list of conditions and the following disclaimer in the
 #    documentation and/or other materials provided with the distribution.
 # 3. All advertising materials mentioning features or use of this software
 #    must display the following acknowledgement:
 #        This product includes software developed by InterServer, Inc and
 #        its contributors.
 # 4. Neither the name of InterServer, Inc nor the names of its
 #    contributors may be used to endorse or promote products derived
 #    from this software without specific prior written permission.
 #
 # THIS SOFTWARE IS PROVIDED BY INTERSERVER, INC. AND CONTRIBUTORS
 # ``AS IS'' AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED
 # TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR
 # PURPOSE ARE DISCLAIMED.  IN NO EVENT SHALL THE COMPANY OR CONTRIBUTORS
 # BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
 # CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
 # SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
 # INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
 # CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
 # ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 # POSSIBILITY OF SUCH DAMAGE.
 #/


# for freebsd mount with acls
# on linux mount with acl

# disable with -remove

if [ ! -e /proc/user_beancounters ]; then
	if [ "$(grep acl /etc/fstab)" = "" ]; then
        		exit;
	fi
fi


if [ ! -e /usr/bin/setfacl ]; then
        yum -y install acl
fi

if [ ! -e /usr/bin/setfacl ]; then
        exit;
fi

# disable on cloudlinux
cloud=0;
if [ -e /usr/share/cagefs ]; then
	cloud=1;
fi

user=nobody;
if [ -e /var/webuzo ]; then
	user=apache;
fi

echo "using user $user";

for i in /usr/bin/perl /usr/local/bin/perl /bin/ping /bin/traceroute /usr/bin/gcc /bin/gunzip /bin/tar /usr/bin/lynx /usr/bin/cc /usr/bin/i386-redhat-linux-gcc /usr/bin/php /usr/local/bin/php /usr/bin/find /usr/bin/stat /usr/bin/locate /usr/bin/wget /bin/cat /bin/ls /bin/ln /usr/bin/unzip /usr/bin/zip /bin/uname /usr/bin/curl /usr/kerberos/bin/ftp; do
        if [ -x $i ]; then
                if [ -e /admin/.info/acl_exclude ]; then
                        if [ ! "$(grep "^$i$" /admin/.info/acl_exclude)" = "" ]; then
                                echo "$i is excluded in /admin/.info/acl_exclude";
                                # lets remove acl's on the excluded
                                setfacl -b $i
                        else
				if [ "$1" = "-remove" -o "$1" = "-disable" -o "$cloud" = "1" ]; then
					setfacl -b $i
					echo "Removed acl on $i"
				else
                                	setfacl -m u:$user:---,g:$user:--- $i
                                	echo "Added on $i";
				fi
                        fi
                else
			if [ "$1" = "-remove" -o "$cloud" = "1" ]; then
                                        setfacl -b $i
                                        echo "Removed acl on $i"
			else
                        	setfacl -m u:$user:---,g:$user:--- $i
                        	echo "Added acl on $i";
			fi
                fi
        else
                echo "$i is not executable";
        fi
done


echo "Protections Enabled";

