#!/bin/sh

 #-
 # Copyright (c) 2006 InterServer, Inc.
 # All rights reserved.
 #
 # Redistribution and use in source and binary forms, with or without
 # modification, are permitted provided that the following conditions
 # are met:
 # 1. Redistributions of source code must retain the above copyright
 #    notice, this list of conditions and the following disclaimer.
 # 2. Redistributions in binary form must reproduce the above copyright
 #    notice, this list of conditions and the following disclaimer in the
 #    documentation and/or other materials provided with the distribution.
 # 3. All advertising materials mentioning features or use of this software
 #    must display the following acknowledgement:
 #        This product includes software developed by InterServer, Inc and
 #        its contributors.
 # 4. Neither the name of InterServer, Inc nor the names of its
 #    contributors may be used to endorse or promote products derived
 #    from this software without specific prior written permission.
 #
 # THIS SOFTWARE IS PROVIDED BY INTERSERVER, INC. AND CONTRIBUTORS
 # ``AS IS'' AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED
 # TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR
 # PURPOSE ARE DISCLAIMED.  IN NO EVENT SHALL THE COMPANY OR CONTRIBUTORS
 # BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
 # CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
 # SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
 # INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
 # CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
 # ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 # POSSIBILITY OF SUCH DAMAGE.
 #/

# FIX ME freebsd does not increase rule number after 10

if [ "$1" = "" ]; then
        echo "Usage ./blockip ip.address"
        exit;
fi

export PATH=/sbin:/usr/sbin:/usr/local/sbin:/bin:/usr/bin:/usr/local/bin

check="$(echo $1 | grep .)"
if [ "$check" = "" ]; then
	echo "Invalid ip"
	exit;
fi

if [ -e /etc/master.passwd ]; then
	check_ip=`ipfw list | grep deny | grep $1`;
	if [ ! "$check_ip" = "" ]; then
		echo "$1 already blocked"	
		exit;
	fi
	check=`ipfw list | grep ^01 | cut -d " " -f1 | tail -n 1`;
	if [ "$check" = "" ]; then
		rule=1000;
	else
		rule=`expr $check + 1`;
	fi
	echo "Rule: $rule";
	ipfw add $rule deny ip from $1 to any
	#if [ "$2" = "-blackhole" ]; then
	/sbin/route add -net $1 -netmask 255.255.255.255 127.0.0.1 -blackhole
	#fi

else
	check=`iptables -L -n | grep ^DROP | awk '{print $4 }' | grep ^$1$`;
	if [ "$check" = "" ]; then
		# use csf if available
		if [ -e /usr/sbin/csf ]; then
			# only if not disabled of course
			if [ ! -e /etc/csf/csf.disable ]; then
				/usr/sbin/csf --deny $1
				exit;
			else
				echo 'CSF disabled. Iptables being called directly';
			fi
		fi
		iptables -I INPUT -s $1 -j DROP
		# Make sure that he never hears from us again:
		iptables -I OUTPUT -s $1 -j DROP
		echo "Blocked $1";
	else
		echo "$1 blocked already";
	fi
fi
