#!/usr/bin/perl

$yum = 0;
@CT=split(/\n/,`crontab -l`);
foreach $line (@CT) {
        if ($line =~ /\/admin\/kvmgettemplate.sh/) {
                $yum = 1;
                quit;
        }
}
if (!$yum) {
        if (! -d "/root/tmp") {
                system("mkdir","-p","/root/tmp");
        }
        if (-e "/root/tmp/.crontab") {
                unlink("/root/tmp/.crontab");
        }
        @CT=grep(!/\/admin\/kvmgettemplate.sh/, @CT);
        push(@CT,int(rand(60)) . " " . int(rand(6)) . " * * * /admin/kvmgettemplate.sh >/dev/null 2>&1");
        open(CR,">/root/tmp/.crontab");
        foreach $line (@CT) {
                print CR "$line\n";
        }
        close(CR);
        system("crontab","/root/tmp/.crontab");
        unlink("/root/tmp/.crontab");
}

