#!/bin/bash

# for interserver mailchannels servers with cpanel
# clean up queue
# remove frozens
# runs good ips if exists
# hooks into asl whitelist
# scans tmp folders for cagefs if cron has tmp in it (malware usually) 
# if imunify exists run protect blamer and send files over for scans. This is because upload scanner on imunify servers does not hook into /opt/scan.sh
# killalling off known bad processes as well
debug=0;

MYDIR=`pwd`;

function killprocs() {
	killall -9 2.mcm.x86_64 1.mcm.x86_64 mcm.x86_64 entry6 >/dev/null 2>&1
}

if [ -e /usr/local/cpanel ]; then
	killprocs
	if [ ! -e /etc/exim.conf.local ]; then
		if [ "$debug" = "1" ]; then
			echo 'no exim.conf.local';
		fi
		exit;
	fi

	check=`grep mailchannels /etc/exim.conf.local`;
	if [ "$check" = "" ]; then
		if [ "$debug" = "1" ]; then
			echo 'no mailchannels';
		fi
		exit;
	fi
elif [ -d /usr/local/directadmin ]; then
	killprocs
	if [ ! -f /etc/exim.authenticators.post.conf ]; then
		if [ "$debug" = "1" ]; then
                        echo 'no mailchannels for directadmin';
                fi
		exit;
	fi
else
	if [ "$debug" = "1" ]; then
        	echo 'not cpanel or da';
        fi
	exit;
fi

if [ "$debug" = "0" ]; then
        echo() { :; }
fi


lock_file="/root/tmp/_mccleanqueue";


if [ -e $lock_file ]; then
	if [ "$(( $(date +"%s") - $(stat -c "%Y" $lock_file) ))" -gt "6600" ]; then
                if [ "$debug" = "1" ]; then
			echo "ERROR: Lock file is too old"
		fi
		/bin/rm $lock_file > /dev/null 2>&1
        else
		if [ "$debug" = "1" ]; then
                	echo "ERROR: Lock file found, exiting";
		fi
                exit;
        fi
fi

check=`ps auxw | grep /etc/cron.hourly/mccleanqueue | grep -v grep | wc -l`;

if [ "$check" -gt "4" ]; then
	if [ "$debug" = "1" ]; then
		echo "$check processes running already for mccleanqueue";
	fi
	exit;
fi

touch $lock_file


if [ "$debug" = "1" ]; then

	/admin/exigrep -1d 
	/admin/exi rmfrozen
	/admin/exi scancwd faster
else
	/admin/exigrep -1d >/dev/null 2>&1
        /admin/exi rmfrozen >/dev/null 2>&1
        /admin/exi scancwd faster >/dev/null 2>&1
fi

# cpanel specific
# check crons and cagefs for common cron exploits
if [ -e /usr/local/cpanel ]; then
	if [ -x /admin/modsecurity/goodips.sh ]; then
		/admin/modsecurity/goodips.sh > /dev/null 2>&1
	fi
	if [ -x /admin/modsecurity/buildaslwhitelist.sh ]; then
		if [ -f /etc/asl/whitelist ]; then
			/admin/modsecurity/buildaslwhitelist.sh > /dev/null 2>&1
		fi
	fi

	# imunify is more efficiant
	if [ ! /usr/bin/imunify360-agent ]; then
		if [ -d /var/spool/cron ]; then
			for tmpusers in `grep -lri /tmp/ /var/spool/cron | cut -d/ -f5 | grep -v root`; do
				if [ -e /var/cpanel/users/$tmpusers ]; then
					tmpuserhomedir=`cat /etc/passwd | grep ^$tmpusers: | cut -d: -f6`;
					if [ -d $tmpuserhomedir/.cagefs/tmp ]; then
						echo "Found user $tmpusers with homedir $tmpuserhomedir and scanning with clamav";
						cd $tmpuserhomedir/.cagefs/tmp
						if [ "$debug" = "1" ]; then
							/admin/clamscan shelldb q
						else
							/admin/clamscan shelldb q >/dev/null 2>&1
						fi
						cd $MYDIR
					fi
				fi
			done
		fi
	fi
	if [ -d /var/spool/exim ]; then
		exim_tidydb -t 1d /var/spool/exim wait-remote_smtp > /dev/null 2>&1
		exim_tidydb -t 1h /var/spool/exim retry > /dev/null 2>&1
	fi

	# run if server has imunify
	if [ -f /root/.swift/config ]; then
		if [ -f /usr/bin/imunify360-agent ]; then
			ts=`date -d '1 hour ago' +%s`;
			if [ "$ts" = "" ]; then
				echo 'error could not get timestamp 1 hour ago';
			else
				for imfile in `timeout 120 imunify360-agent proactive list --since ${ts} | awk '{print $7}' | grep ^/home`; do 
					/admin/ml/send $imfile
				done
			fi
		fi
	fi	
fi

/bin/rm $lock_file > /dev/null 2>&1
