#!/bin/sh

# /************************************************************************************\
# * Trouble Free Admin Center                                                          *
# * (c)2002 Interserver.net                                                            *
# * ---------------------------------------------------------------------------------- *
# * Description: Set default /etc/my.cnf file                                          *
# \************************************************************************************/

if [ -e /etc/my.cnf ]; then
	mv -f -v /etc/my.cnf /etc/my.cnf.old
fi

cat > /etc/my.cnf <<EOF
[mysqld]
	default-storage-engine=MYISAM
	local-infile=0
	innodb_file_per_table=1
	max_connections=500
        max_user_connections=100
	open_files_limit = 10000
	local-infile = 0
	max_allowed_packet = 512M
	query_cache_type = 0
	query_cache_size = 0
	join_buffer_size = 1M
	tmp_table_size = 32M
	max_heap_table_size = 32M
	innodb_log_file_size= 100M
	sql_mode=""

EOF

echo 'Updated /etc/my.cnf';
echo
cat /etc/my.cnf
echo
