#!/bin/sh
# WebPanel by VDI
# This code has been reproduced under permission from VDI

hostname=`hostname`

if [ -e "/usr/bin/mysql" ]; then
        mysql='/usr/bin/mysql'
        mysqladmin='/usr/bin/mysqladmin'
else
        mysql='/usr/local/bin/mysql'
        mysqladmin='/usr/local/bin/mysqladmin'
fi



user=$1;
if [ "$user" = "" ]; then
        echo "Syntax: mysqldeluserdb <user>"
	exit
fi
if [ "$user" = "root" ]; then
        exit
fi  

$mysqladmin -u root drop $user <<EOM
y
EOM
$mysql mysql -u root <<END_OF_DATA
DELETE from user WHERE user='$user';
DELETE from db WHERE user='$user';
END_OF_DATA
$mysqladmin -u root reload <<EOM
EOM

