#!/bin/sh
# WebPanel by VDI
# This code has been reproduced under permission from VDI

if [ ! -e /etc/redhat-release ]; then
	echo 'Requires redhat';
	exit;
fi

if [ ! -d /var/lib/mysql ]; then
	echo 'MySQL not found in /var/lib/mysql';
	exit;
fi

hostname=`hostname`
#. /scripts/mysqlinfo



if [ -e "/usr/bin/mysql" ]; then
	mysql='/usr/bin/mysql'
	mysqladmin='/usr/bin/mysqladmin'
else
	mysql='/usr/local/bin/mysql'
	mysqladmin='/usr/local/bin/mysqladmin'
fi
   
user=$1;
pass=$2;
if [ "$user" = "" ]; then
        echo "Syntax: mysqladduserdb <user> <newpass>"
	exit
fi
if [ "$pass" = "" ]; then
        echo "Syntax: mysqladduserdb <user> <newpass>"
	exit
fi
if [ "$user" = "root" ]; then
        exit;
fi


if [ -e /var/lib/mysql/$user ]; then
	echo 'DB exists already';
	exit;
fi
        
#$mysqladmin -u root drop $user
$mysqladmin -u root create $user

$mysql mysql -u root <<END_OF_DATA
DELETE from user WHERE user='$user';
insert into user (host,user,password) values('localhost','$user',password('$pass')) ;
insert into user (host,user,password) values('$hostname','$user',password('$pass')) ;
DELETE from db WHERE user='$user';
INSERT INTO db (host,db,user,Select_priv,Alter_priv,Insert_priv,Update_priv,Delete_priv,Create_priv,Drop_priv)
        VALUES ('localhost','$user','$user','Y','Y','Y','Y','Y','Y','Y');
INSERT INTO db (host,db,user,Select_priv,Alter_priv,Insert_priv,Update_priv,Delete_priv,Create_priv,Drop_priv)
        VALUES ('$hostname','$user','$user','Y','Y','Y','Y','Y','Y','Y');
END_OF_DATA
$mysqladmin -u root reload <<EOM
EOM

echo "DB $user created";
