#!/bin/sh

 #-
 # Copyright (c) 2006 InterServer, Inc.
 # All rights reserved.
 #
 # Redistribution and use in source and binary forms, with or without
 # modification, are permitted provided that the following conditions
 # are met:
 # 1. Redistributions of source code must retain the above copyright
 #    notice, this list of conditions and the following disclaimer.
 # 2. Redistributions in binary form must reproduce the above copyright
 #    notice, this list of conditions and the following disclaimer in the
 #    documentation and/or other materials provided with the distribution.
 # 3. All advertising materials mentioning features or use of this software
 #    must display the following acknowledgement:
 #        This product includes software developed by InterServer, Inc and
 #        its contributors.
 # 4. Neither the name of InterServer, Inc nor the names of its
 #    contributors may be used to endorse or promote products derived
 #    from this software without specific prior written permission.
 #
 # THIS SOFTWARE IS PROVIDED BY INTERSERVER, INC. AND CONTRIBUTORS
 # ``AS IS'' AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED
 # TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR
 # PURPOSE ARE DISCLAIMED.  IN NO EVENT SHALL THE COMPANY OR CONTRIBUTORS
 # BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
 # CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
 # SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
 # INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
 # CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
 # ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 # POSSIBILITY OF SUCH DAMAGE.
 #/


if [ -e /etc/master.passwd ]; then
	netstat -an | grep -v LISTEN | grep -v 127.0.0.1 | grep -v "::1.443" | grep -v "*.80" | grep -v "*.*" | grep ^tcp | awk '{print $5 }' | cut -d. -f1-4 | sort | uniq -c | sort
else
        if [ -d /usr/share/doc/centos-release-4  ]; then
		netstat -an | grep : | grep -v 0.0.0.0 | grep -v "*" | awk '{print $5 }' | sed s#"::ffff:"#""#g | cut -d. -f1-4 | cut -d: -f1 | sort | uniq -c | sort -n
	elif [ -d /etc/container -o -d /usr/share/doc/centos-release-5 -o -d /usr/share/doc/centos-release-3 ]; then
		 netstat -an | grep : | awk '{print $5}' | grep -v 0.0.0.0 | grep -v "*" | grep -v ^::1: | sed s#"::ffff:"#""#g | cut -d. -f1-4 | cut -d: -f1 | sort | uniq -c | sort -n
        else
                netstat -an | grep : | grep -v 0.0.0.0 | grep -v ":::*" | awk '{print $5 }' | cut -d: -f1 | sort | uniq -c | sort -n
        fi
fi
