#!/bin/sh

# John Quaglieri
# john@interserver.net
# block outgoing ports for user nobody
# this is helpful in blocking downloads from insecure php scripts

 #-
 # Copyright (c) 2006 InterServer, Inc.
 # All rights reserved.
 #
 # Redistribution and use in source and binary forms, with or without
 # modification, are permitted provided that the following conditions
 # are met:
 # 1. Redistributions of source code must retain the above copyright
 #    notice, this list of conditions and the following disclaimer.
 # 2. Redistributions in binary form must reproduce the above copyright
 #    notice, this list of conditions and the following disclaimer in the
 #    documentation and/or other materials provided with the distribution.
 # 3. All advertising materials mentioning features or use of this software
 #    must display the following acknowledgement:
 #        This product includes software developed by InterServer, Inc and
 #        its contributors.
 # 4. Neither the name of InterServer, Inc nor the names of its
 #    contributors may be used to endorse or promote products derived
 #    from this software without specific prior written permission.
 #
 # THIS SOFTWARE IS PROVIDED BY INTERSERVER, INC. AND CONTRIBUTORS
 # ``AS IS'' AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED
 # TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR
 # PURPOSE ARE DISCLAIMED.  IN NO EVENT SHALL THE COMPANY OR CONTRIBUTORS
 # BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
 # CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
 # SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
 # INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
 # CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
 # ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 # POSSIBILITY OF SUCH DAMAGE.
 #/


# exclude file is located at /admin/.info/nobody_allow 

# args
ports='21 80';
owner='99';

if [ "$1" = "--check" ]; then
	check=`/sbin/iptables -L -n | grep "tcp dpt:80 OWNER UID match 99 reject-with icmp-port-unreachable"`;
	if [ ! "$check" = "" ]; then
		echo 'Check OK';
		exit 1;
	else
		echo 'Check FAILED';
	fi
fi

# check for ip tables
if [ -e /sbin/iptables ]; then
	for port in $ports; do
		/sbin/iptables -I OUTPUT --protocol tcp --dport $port -m owner --uid-owner $owner -j REJECT
	done
	if [ -e /admin/.info/nobody_allow ]; then
		for ip in `cat /admin/.info/nobody_allow`; do
			for port in $ports; do
				echo "Allowing outgoing connection on $port to $ip for uid $owner";
				/sbin/iptables -I OUTPUT --protocol tcp -d $ip --dport $port -m owner --gid-owner $owner -j ACCEPT
			done
		done
	fi
fi
