#!/usr/bin/env bash

if [ ! -f /etc/ssh/ssh_host_ed25519_key-cert.pub ]; then
	echo 'Missing /etc/ssh/ssh_host_ed25519_key-cert.pub';
	exit;
fi

if [ -f /admin/configs/ssh/ssh_certs_authorized_keys ]; then
	if [ -f /root/.ssh/authorized_keys ]; then
		/bin/rm -v /root/.ssh/authorized_keys
	fi

	if [ -f /root/.ssh/authorized_keys2 ]; then
		/bin/rm -v /root/.ssh/authorized_keys2
	fi

	cp -v /admin/configs/ssh/ssh_certs_authorized_keys /root/.ssh/authorized_keys
	ln -v /root/.ssh/authorized_keys /root/.ssh/authorized_keys2

else
	echo 'Missing /admin/configs/ssh/ssh_certs_authorized_keys';
fi

