#!/bin/sh

if [ -d /usr/local/directadmin ]; then
	exit;
fi

if [ ! -x /usr/sbin/zfs ]; then
	exit;
fi

#/usr/sbin/setquota cassmancatechismcom 1024000000 1126400000 0 0 /home
if [ ! "$1" = "" ]; then
        if [ -d /home/$1 ]; then
                /admin/storage/fixquota $1
        fi
fi


