# modified 7/3/2025
interface: 0.0.0.0
interface: ::0
access-control: 127.0.0.0/8 allow  # (allow queries from the local host)
                access-control: 66.45.224.0/19 allow
                access-control: 69.10.32.0/19 allow
                access-control: 68.168.208.0/20 allow
                access-control: 209.159.144.0/20 allow
                access-control: 66.23.224.0/20 allow
                access-control: 173.214.160.0/20 allow
                access-control: 206.72.192.0/20 allow
                access-control: 199.231.184.0/21 allow
                access-control: 192.64.80.0/21 allow
                access-control: 162.216.112.0/22 allow
                access-control: 162.250.120.0/21 allow
                access-control: 162.220.160.0/21 allow
                access-control: 162.246.16.0/21 allow
                access-control: 104.37.184.0/21 allow
                access-control: 104.218.48.0/21 allow
                access-control: 208.73.200.0/21 allow
                access-control: 216.158.224.0/20 allow
                access-control: 174.138.176.0/20 allow
                access-control: 173.225.96.0/20 allow
                access-control: 67.211.208.0/20 allow
                access-control: 64.20.32.0/19 allow
                access-control: 204.13.232.0/21 allow
		access-control: 161.129.64.0/21 allow
		access-control: 162.245.184.0/21 allow
		access-control: 198.96.88.0/21 allow
                #hd
                access-control: 216.219.80.0/20 allow
                access-control: 205.209.96.0/19 allow
                access-control: 69.164.240.0/20 allow
                access-control: 74.50.64.0/19 allow
                access-control: 67.217.48.0/20 allow

                #ipv6
                access-control: 2604:A00::/32 allow
