#!/bin/bash

export PATH=/usr/local/cpanel/3rdparty/lib/path-bin:/usr/local/cpanel/3rdparty/lib/path-bin:/usr/local/cpanel/3rdparty/lib/path-bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/opt/cpanel/composer/bin
# add ea-74
# groupupdate cloudlinux

if [ -d /usr/local/cpanel ]; then
	yum -y install ea-php74-php-litespeed ea-php74-php-zip ea-php74-php-xml ea-php74-php-opcache ea-php74-php-mysqlnd ea-php74-php-mbstring ea-php74-php-intl ea-php74-php-imap ea-php74-php-iconv ea-php74-php-gettext ea-php74-php-gd ea-php74-php-fileinfo ea-php74-php-exif ea-php74-php-common ea-php74-php-calendar ea-php74-php-bz2 ea-php74-php-bcmath ea-php74-php-memcached ImageMagick-devel ea-php74-php-devel ea-php74-pear ea-php74-php-curl ea-apache24-mod_env
	
	if [ -x /usr/sbin/cagefsctl ]; then
		/usr/sbin/cagefsctl --addrpm ImageMagick

		# python and others
		yum -y groupinstall alt-python
		yum -y groupinstall alt-nodejs6 alt-nodejs8 alt-nodejs9 alt-nodejs10 alt-nodejs11 alt-nodejs12
                yum -y groupinstall alt-ruby

		yum -y install alt-php52-ffmpeg.x86_64 alt-php53-ffmpeg.x86_64 alt-php54-ffmpeg.x86_64 alt-php55-ffmpeg.x86_64 alt-php56-ffmpeg.x86_64 alt-php70-ffmpeg.x86_64 alt-php71-ffmpeg.x86_64 alt-php72-ffmpeg.x86_64

		# new add php 8.0
		yum -y install ea-php80-php-zip.x86_64 ea-php80-php-xml.x86_64 ea-php80-php-sockets.x86_64 ea-php80-php-tidy.x86_64 ea-php80-php-soap.x86_64 ea-php80-php-pspell.x86_64 ea-php80-php-snmp.x86_64 ea-php80-php-pdo.x86_64 ea-php80-php-opcache.x86_64 ea-php80-php-mysqlnd.x86_64 ea-php80-php-mbstring.x86_64 ea-php80-php-litespeed.x86_64 ea-php80-php-intl.x86_64 ea-php80-php-imap.x86_64 ea-php80-php-iconv.x86_64 ea-php80-php-gmp.x86_64 ea-php80-php-gettext.x86_64 ea-php80-php-gd.x86_64 ea-php80-php-ftp.x86_64 ea-php80-php-fileinfo.x86_64 ea-php80-php-exif.x86_64 ea-php80-php-enchant.x86_64 ea-php80-php-devel.x86_64 ea-php80-php-curl.x86_64 ea-php80-php-common.x86_64 ea-php80-php-cli.x86_64 ea-php80-php-calendar.x86_64 ea-php80-php-bz2.x86_64 ea-php80-php-bcmath.x86_64 ea-php80-libc-client-static.x86_64 ea-php80-php-memcached.x86_64

	fi

	#if [ -x /opt/cpanel/ea-php74/root/usr/bin/pecl ]; then
	#	timeout 200 printf "\n" | /opt/cpanel/ea-php74/root/usr/bin/pecl install imagick
	#fi

	#if [ -x /opt/cpanel/ea-php72/root/usr/bin/pecl ]; then
        #        timeout 200 printf "\n" | /opt/cpanel/ea-php72/root/usr/bin/pecl install imagick
        #fi
	
	# fails to build
	#if [ -x /opt/cpanel/ea-php80/root/usr/bin/pecl ]; then
        #        timeout 200 /opt/cpanel/ea-php80/root/usr/bin/pecl install imagick
        #fi


	if [ -x /usr/sbin/cagefsctl ]; then
		/usr/sbin/cagefsctl --force-update
	fi

	if [ -x /admin/res ]; then
		/admin/res httpd ,
	fi
fi
