template standard/%g/%u {
     cpu {
         #200000 and cpu.cfs_period_us to 1000000
         cpu.cfs_period_us=200000;
         cpu.cfs_quota_us=200000;
         cpu.shares=100;
     }
     memory {
         memory.limit_in_bytes = 2048m;
     }

     #0 to 1000
     blkio {
                # 10MBPS is 10485760"
		# 100 mbps is 100000000
                # 8/0 is major minor of /dev/sda     
                blkio.throttle.read_bps_device = "8:0 25000000";
                blkio.throttle.write_bps_device = "8:0 25000000";
                # iops / s
                blkio.throttle.read_iops_device = "8:0 1024";
                blkio.throttle.write_iops_device = "8:0 1024";
     }

     pids {
                pids.max = 20;
        }
}

template storage/%g/%u {
     cpu {
         #200000 and cpu.cfs_period_us to 1000000
         cpu.cfs_period_us=200000;
         cpu.cfs_quota_us=200000;
         cpu.shares=100;
     }
     memory {
         memory.limit_in_bytes = 2048m;
     }

     #0 to 1000
     blkio {
                # 10MBPS
                # 8/0 is major minor of /dev/sda
                blkio.throttle.read_bps_device = "8:0 100000000";
                blkio.throttle.write_bps_device = "8:0 100000000";
                # iops / s
                blkio.throttle.read_iops_device = "8:0 1024";
                blkio.throttle.write_iops_device = "8:0 1024";
     }

     pids {
                pids.max = 20;
        }

}


template boost2/%g/%u {
     cpu {
         #200000 and cpu.cfs_period_us to 1000000
         cpu.cfs_period_us=300000;
         cpu.cfs_quota_us=300000;
         cpu.shares=200;
     }
     memory {
         memory.limit_in_bytes = 4096m;
     }

     #0 to 1000
     blkio {
                # 10MBPS
                # 8/0 is major minor of /dev/sda
                blkio.throttle.read_bps_device = "8:0 50000000";
                blkio.throttle.write_bps_device = "8:0 50000000";
                # iops / s
                blkio.throttle.read_iops_device = "8:0 2048";
                blkio.throttle.write_iops_device = "8:0 2048";
     }

     pids {
                pids.max = 40;
        }

}

template boost4/%g/%u {
     cpu {
         #200000 and cpu.cfs_period_us to 1000000
         cpu.cfs_period_us=400000;
         cpu.cfs_quota_us=400000;
         cpu.shares=300;
     }
     memory {
         memory.limit_in_bytes = 8192m;
     }

     #0 to 1000
     blkio {
                # 10MBPS
                # 8/0 is major minor of /dev/sda
                blkio.throttle.read_bps_device = "8:0 100000000";
                blkio.throttle.write_bps_device = "8:0 100000000";
                # iops / s
                blkio.throttle.read_iops_device = "8:0 4192";
                blkio.throttle.write_iops_device = "8:0 4192";
     }

     pids {
                pids.max = 60;
        }

}


